## export GPG details
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
sudo: false
language: java
services:
  - docker
cache:
  directories:
    - "$HOME/.cache"
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn install deploy -B -U -Prelease"
  skip_cleanup: true
  on:
    tags: false
